### ISSUE TITLE
Glacier docker is not working

### ISSUE THREAD

**Issue by daveoon** [zeroc-ice/ice-dockerfiles#2]
There is no logs or output and i have no idea whats going on. Is there anyone to assist? I followed the instruction and setup the both server and client endpoints as i require bidirectional communication.

**Comment by daveoon** [comment]
There is no logs or output and i have no idea whats going on. Is there anyone to assist? I followed the instruction and setup the both server and client endpoints as i require bidirectional communication.

**Comment by externl** [comment]
Sorry for the late responose, @daveoon.  Do you have your client and server setup and working outside of docker?

**Comment by daveoon** [comment]
no problem.  i have up this solution as the mumble client is more convenient and it satisfy most of my requirements to control the connected users. thank you
