### ISSUE TITLE
how to deploy the distribut ice registy and the node

### ISSUE THREAD

**Issue by chuckpu** [zeroc-ice/ice-dockerfiles#3]
1、How to deploy the distribut ice registy with docker or K8S？
2、How to automatic deploy node service with docker？

**Comment by externl** [comment]
@chuckpu You can deploy IceGrid registry and nodes with Docker like you would any other docker application. 

Our [documentation](https://doc.zeroc.com/ice/3.7/ice-services/icegrid) is a great source of information regarding configuring IceGrid.
