### ISSUE TITLE
docker run zeroc/icegridregistry, Error response from daemo

### ISSUE THREAD

**Issue by jhhe66** [zeroc-ice/ice-dockerfiles#4]
docker run --name some-icegridregistry -v /path/to/config:/etc/icegridregistry.conf:ro -v /path/to/folder:/var/lib/ice/icegrid -d zeroc/icegridregistry

Error response from daemon: Cannot restart container some-icegridregistry: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/path/to/config\\\" to rootfs \\\"/mnt/docker-data/overlay/6f931587ed0dec402b98c02966ea7bc14c6706eac23a23b8c767095546e6364f/merged\\\" at \\\"/mnt/docker-data/overlay/6f931587ed0dec402b98c02966ea7bc14c6706eac23a23b8c767095546e6364f/merged/etc/icegridregistry.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by jhhe66** [comment]
I try again: docker run --name some-icegridregistry -d zeroc/icegridregistry

but output:
-! 05/22/19 02:01:33.708 warning: unknown property: `IceGrid.Registry.Data'

**Comment by externl** [comment]
> docker run --name some-icegridregistry -v /path/to/config:/etc/icegridregistry.conf:ro -v /path/to/folder:/var/lib/ice/icegrid -d zeroc/icegridregistry

> Error response from daemon: Cannot restart container some-icegridregistry: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused "rootfs_linux.go:58: mounting \"/path/to/config\" to rootfs \"/mnt/docker-data/overlay/6f931587ed0dec402b98c02966ea7bc14c6706eac23a23b8c767095546e6364f/merged\" at \"/mnt/docker-data/overlay/6f931587ed0dec402b98c02966ea7bc14c6706eac23a23b8c767095546e6364f/merged/etc/icegridregistry.conf\" caused \"not a directory\""": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

It sounds like you're trying to mount a directory when a file is required. `/path/to/config` must be an IceGrid Registry config file.

EDIT: As well, ` /path/to/config` and `/path/to/folder` must be real.

**Comment by tq02ksu** [comment]
Yes, I faced the same problem, and icegirdregistry output less log, sometimes, only exit 1.

After some experiments,  I get the runnable configuration file as follow:
```properties
IceGrid.Registry.Client.Endpoints=tcp -p 4061
IceGrid.Registry.Server.Endpoints=tcp
IceGrid.Registry.Internal.Endpoints=tcp
IceGrid.Registry.LMDB.Path=/var/lib/ice/icegrid/registry/
```
save to a file "/path/to/icegridregistry.conf", then
```
docker run -v /Users/tq02ksu/workspace/icegrid/config:/etc/icegridregistry.conf:ro -d zeroc/icegridregistry
```
and it works
