### ISSUE TITLE
Deployed application in nodes not working

### ISSUE THREAD

**Issue by joselsegura** [zeroc-ice/ice-dockerfiles#6]
Hi!

I created a docker-compose to execute the registry and one node without any problem. I'm able to connect to the registry from my host machine with `icegridadmin` and I'm able to show the list of nodes (node in my case), loading an application from XML and see the list of servers.

I tried a very simple application with no Ice usage (just a C++ hello world with no Ice at all).

I'm totally unable to enable the server and unable to retrieve the stdout or stderr from the server.

If I read the stderr from the node, I can see the problem:

```Ice.FileException: exception ::Ice::FileException
{
    error = 13
    path = /var/lib/ice/icegrid/servers/helloworld/config/config
}```

I was able to exec bash inside the container and see the structure of /var/lib/ice directories, and apparently everything is set in place. If I'm correct, error 13 indicates that it's a permission problems, so I tried just to be sure to change the whole /var/lib/ice permissions to root:root ownership and 777 mode, but it still refuses to start the server, showing the same error.

Do you have a clue about what I'm doing incorrectly?

**Comment by pepone** [comment]
Most probably the server is run as "nobody" user, see https://doc.zeroc.com/ice/3.7/ice-services/icegrid/icegrid-server-activation#id-.IceGridServerActivationv3.7-ActivatingServerswithSpecificUserIDs

**Comment by joselsegura** [comment]
Interesting. I modified my XML to define the "root" user and now it tries to run it, but it still fails, with a new error (this time, at server level).

At the same time I extended your image because I need to run Python code inside the container (used yours as FROM and add a new `apt-get install` to install Python + Python Ice libraries

```
>>> server show pyhello stderr
2023-02-17 11:47:16.060124 helloworld.py: error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Ice/__init__.py", line 1546, in doMain
    Application._communicator = initialize(args, initData)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Ice/__init__.py", line 1033, in initialize
    communicator = IcePy.Communicator(args, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Ice.SocketException: Ice.SocketException:
Cannot assign requested address
```

Are not able the servers to listen in any port? I didn't put anything in the Ice configuration, so I don't know what the problem is now...

**Comment by pepone** [comment]
What endpoint did you configure in your server? seems the server is failing to assign the requested address.

Also try enabling network tracing in your server by setting `Ice.Trace.Network` property to `3`

**Comment by joselsegura** [comment]
The XML section regarding this specific server

```
<server id="pyhello" activation="always" exe="./helloworld.py" pwd="/" user="root">
  <properties>
    <property name="Ice.StdOut" value="${server.distrib}/out"/>
    <property name="Ice.StdErr" value="${server.distrib}/err"/>
  </properties>
</server>
```

As you can see, I didn't use any object adapter, so no endpoints.  You can see the specific server configration file above:

```
cat /var/lib/ice/icegrid/servers/pyhello/config/config
# Configuration file (02/17/23 11:47:15.354)

# Server configuration
Ice.Admin.ServerId=pyhello
Ice.Admin.Endpoints=tcp -h localhost
Ice.ProgramName=0.0-login
# Server descriptor properties
Ice.StdOut=/var/lib/ice/icegrid/servers/pyhello/distrib/out
Ice.StdErr=/var/lib/ice/icegrid/servers/pyhello/distrib/err
Ice.Default.Locator=IceGrid/Locator -t:tcp -h registry -p 4061
```

Adding the node configuration:

```❯ cat ice/node1.config
Ice.Default.Locator=IceGrid/Locator -t:tcp -h registry -p 4061
IceGrid.Node.Name=node1
IceGrid.Node.Data=/var/lib/ice/icegrid/node1
IceGrid.Node.Endpoints=tcp
IceGrid.Node.AllowRunningServersAsRoot=1

Ice.StdOut=/var/lib/ice/icegrid/node1/out.txt
Ice.StdErr=/var/lib/ice/icegrid/node1/err.txt```

**Comment by pepone** [comment]
You might want to manually set the `Ice.Admin.Endpoints` in your server descriptor, here IceGrid added the default value `Ice.Admin.Endpoints=tcp -h localhost`.

https://doc.zeroc.com/ice/3.7/ice-services/icegrid/icegrid-and-the-administrative-facility#id-.IceGridandtheAdministrativeFacilityv3.7-EnablingtheAdministrativeFacilityforaDeployedServer,NodeorRegistryReplica

**Comment by joselsegura** [comment]
And what is the problem with that specific endpoint? It should pick one random available port in the container, which is not incorrect AFAIK.

And apart of that, I'm not using that endpoint for anything at all... why should I care about it?

**Comment by pepone** [comment]
>And what is the problem with that specific endpoint? It should pick one random available port in the container, which is not incorrect AFAIK.

Nothing wrong with that endpoint, but for some reason your system is refusing to assign it, `SocketException` comes from a system error when trying to assign it.

> And apart of that, I'm not using that endpoint for anything at all... why should I care about it?

IceGrid uses this endpoint to manage your server.

**Comment by joselsegura** [comment]
Thank you @pepone I was finally able to solve it. I added the property in my application XML and removed the hostname. The docker containers normally doesn't assign "localhost" in the same way as a real computer, so removing it, keep it working, and no security issue is raised because using a normal deployment, the access will be still restricted to the internal Docker network.

Anyways, I think that the current image is not suitable for everybody:

- Lack of Python (and using Ubuntu 16 as base image makes installing a Python version 3.5, too old).
- In Docker, the node is run as root and, as the docs point very clear, the servers will be launched as "nobody", which will make them unable to even read the configuration file, leading into process activation problems.
- The default endpoint for IceGrid.Node.Endpoint doesn't work in Docker

**Comment by externl** [comment]
@joselsegura Thanks for pointing out these issues.

> Lack of Python (and using Ubuntu 16 as base image makes installing a Python version 3.5, too old).

Yes, Ubuntu 16.04 is pretty old now. We'll update it to something newer. 

> In Docker, the node is run as root and, as the docs point very clear, the servers will be launched as "nobody", which will make them unable to even read the configuration file, leading into process activation problems.

Right, we'll see what we can do here. We should probably be running as the `ice` user like we do for normal linux services.

> The default endpoint for IceGrid.Node.Endpoint doesn't work in Docker

The sample configuration on the Docker Hub README of `icegridnode` alludes to this issue. We'll update it to be clearer.

**Comment by joselsegura** [comment]
Mmm sorry, I didn't reach to that part of the README, my fault.

Based on yours, I created a new image more suitable to my needs (newer Python version and so on):

```FROM debian:testing

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    python3 python3-pip python3-zeroc-ice zeroc-icegrid \
    && apt-get clean && rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

VOLUME ["/var/lib/ice/icegrid"]
ENTRYPOINT ["/usr/bin/icegridnode", "--Ice.Config=/etc/icegridnode.conf", "--IceGrid.Node.Data=/var/lib/ice/icegrid"]
```
In my case, I copied and installed a requirements.txt file for my needs, but apart of that steps, the rest is easily replicable.

I agree that using a different user will make it easier to debug/understand the problems.

Thank you very much for your help!
